/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PurchaseAnalyticsListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onThePurchaseAnalyticsListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onThePurchaseAnalyticsListGenerated.onFilterBar().iCheckFilterField("{i18n>PO_ID}");
            Then.onThePurchaseAnalyticsListGenerated.onFilterBar().iCheckFilterField("{i18n>COMPANY_NAME}");
            Then.onThePurchaseAnalyticsListGenerated.onFilterBar().iCheckFilterField("{i18n>currency}");
            Then.onThePurchaseAnalyticsListGenerated.onFilterBar().iCheckFilterField("{i18n>DESCRIPTION}");
            Then.onThePurchaseAnalyticsListGenerated.onFilterBar().iCheckFilterField("{i18n>COUNTRY}");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onThePurchaseAnalyticsListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onThePurchaseAnalyticsListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onThePurchaseAnalyticsListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onThePurchaseAnalyticsListGenerated.onTable().iCheckColumns(undefined, {"PurchaseOrderId":{"header":"{i18n>PO_ID}"},"ItemPosition":{"header":"{i18n>PO_ITEM_POS}"},"CompanyName":{"header":"{i18n>COMPANY_NAME}"},"GrossAmount":{"header":"{i18n>grossAmount}"},"CurrencyCode":{"header":"{i18n>currency}"},"Description":{"header":"{i18n>DESCRIPTION}"},"OverallStatus":{"header":"{i18n>OVERALL_STATUS}"},"Country":{"header":"{i18n>COUNTRY}"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onThePurchaseAnalyticsListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onThePurchaseAnalyticsListGenerated.onTable().iCheckRows();

            When.onThePurchaseAnalyticsListGenerated.onTable().iPressRow(0);
            Then.onThePurchaseAnalyticsObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});